name: Node CI

on:
  push:
    branches: [ "main" ]  # or any other branch you'd like
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # choose the Node version you need

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test