name: Postman Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # ou outra versão desejada

      - name: Instalar newman
        run: npm install --global newman

      - name: Executar Postman Collection
        run: |
          newman run ./TaskAPITests.postman_collection.json \
            --reporters cli
